### ISSUE TITLE
Twitch is onto us

### ISSUE THREAD

**Issue by avi12** [MarkM-dev/Previews#102]
![image](https://user-images.githubusercontent.com/6422804/201776052-c91dcb6b-92e8-4df3-960a-c84203bcb0d6.png)

I tried disabling the adblocker (shields) on Brave but it still happens
FYI I'm using version 5.8

**Comment by MarkM-dev** [comment]
onto us? i think they know about the extension already, can't be 100% sure yea?
anyway, this screen is called "the purple screen of death". it appears presumably when an ad is supposed to be played on the channel (though it seems arbitrary).

it appears 10-15 seconds after you start watching a preview (which is good, because, well.. previews. it's enough time to see a preview of the channel you want to preview). this is a good compromise.

in the last 2 or 3 months we didn't have the purple screen and some developers and users have figured out that they can watch twitch with no ads or purple screen in the embeds (this used to be a big issue a year ago). it was pretty clear that this (the lack of purple screen) will be temporary and will soon come back, and it did. i'm ok with this - however, i would like to see a more pleasant screen than this purple.

so to make things clear, this purple screen will appear in twitch web embeds, and if you connect lets say via streamlink, then there's some other new screen that looks better when it's ad time.

This isn't something that we can control. and this is ok at it's current practice. twitch needs to show ads.
