### ISSUE TITLE
5000: Content not available

### ISSUE THREAD

**Issue by Dan-Y89** [MarkM-dev/Previews#105]
First of all I want to say thank you, thank you for your very nice Chrome extension.
I noticed that I often have several Twitch pages open in the background and I get the error "5000: Content not available" from time to time.
Stupidly, your extension supports but only up to error 4000. This I also have on, however, this brings nothing for error 5000. So I wanted to please ask for extension of the error code and its fix. I don't know how you fix it, but a text query would be useful there, so that the page reloads when the entered text is found. It's just an example though.
That would be very nice.
Thanks a lot

**Comment by MarkM-dev** [comment]
error 5000 is related to hardware changes on your machine or a persistent issue with your browser or system which requires your attention.
search online about what can cause error 5000 on twitch and follow those steps to permanently fix the issue.
(that's why there is no auto refresher on error 5000 - because it requires your attention and is probably not related to a temporary issue).
