### ISSUE TITLE
The whole stream ui disappears || -- UPDATE: ISSUE FIXED - versions released, awaiting webstore review (a day or two).

### ISSUE THREAD

**Issue by TeamGB** [MarkM-dev/Previews#110]
All the buttons of the stream disappear when I have the extension enabled but they return when I disable it.

![image](https://user-images.githubusercontent.com/99690560/207722738-436ec86a-2322-4152-90a6-c8351fd306dd.png)

what could be the issue?

**Comment by zawe** [comment]
I have the same issue with Firefox 108.0 (64-bit).
After disabling fast forward the UI stopped glitching.

**Comment by FabKaiz** [comment]
Same issue, the ui is getting opacity: 0
![opacity0](https://user-images.githubusercontent.com/73595562/207724605-5a2fe35d-d8f7-40f3-a43a-c1d344f9cf23.png)

**Comment by TeamGB** [comment]
> I have the same issue with Firefox 108.0 (64-bit). Try disabling "Fast-Forward Button" in the Player section, that seemed to solve it for me.

I'm using opera.
I tried this and the left side reappeared:
![image](https://user-images.githubusercontent.com/99690560/207725708-04e96ac1-39f7-40c8-9a7a-63a51966d901.png)

but the right side is still blank:
![image](https://user-images.githubusercontent.com/99690560/207725805-4836f352-5172-4636-85b9-fad1e4533726.png)

**Comment by zawe** [comment]
Try disabling "Screenshot Stream Button" and "FlashBang Defender Button" too.

**Comment by TeamGB** [comment]
those options were already disabled

**Comment by AstrahTV** [comment]
I am having this issue as well. All my UI on the left side just disappears, even though i can change volume and pause and play if i guess where the buttons are normally located. The ui only reappears if i turn off the extension.

**Comment by MarkM-dev** [comment]
Issue has been fixed and versions are out, awaiting websotres review.
meanwhile disable all features that buttons to the player controls.
- screenshot
- Full Screen + Chat Button
- Picture In Picture Button
- Fast-Forward Button 
- Screenshot Stream Button 
- Record Stream Button 
- FlashBang Defender Button 
- Chrome-Cast -> Close Tab Button

**Comment by Sxtrm** [comment]
Having this problem to, recognized about 10 minutes ago. Happy to see that an issue is already created.

Yes, the standard buttons are still working, despite the visibility if known were to click.

Stream preview still works. but all extra player buttons from this browser extension, are leading to the same problem. 
Disabling visibility of all icons on the left or right side of the player, depending on where the extra button´s placed.
except for fullscreen+chat. if activated,  just no buttons remains visible.

I really hope its fixed  soon, the fullscreen+ chat feature is something I´ve missed/wanted for long (using the extension since last week) and I´m so happy that someone made it clickable feature thats just just esc(able) instead of alt+t plus F11 and using multiple buttons to exit.

Using Opera GX.


Have a good One.

Good Work, Dev(´s)!!

**Comment by MarkM-dev** [comment]
Issue has been fixed and versions are out, awaiting websotres review (probably a day or two).
meanwhile disable all features that buttons to the player controls.

Full Screen + Chat Button
Picture In Picture Button
Fast-Forward Button
Screenshot Stream Button
Record Stream Button
FlashBang Defender Button
Chrome-Cast -> Close Tab Button
refresh tab after disabling.

**Comment by MarkM-dev** [comment]
Chrome and Opera versions are now out.
Waiting for Edge and Firefox.
il close the thread when all versions are out.
